# Generated by Django 2.1.7 on 2019-02-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
                ('chioce_A', models.TextField(max_length=20)),
                ('chioce_B', models.TextField(max_length=20)),
                ('chioce_C', models.TextField(max_length=20)),
                ('chioce_D', models.TextField(max_length=20)),
                ('answer', models.TextField(max_length=10)),
                ('category', models.ForeignKey(on_delete=True, to='Post.Category')),
                ('tags', models.ManyToManyField(blank=True, to='Post.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
