# Generated by Django 2.1.7 on 2019-02-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20190220_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
